logging:
  level:
    root: error
    org.springframework: ERROR
    com.gtc: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([%8X{transactionId} %X{MethodName}]) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}) ${LOG_LEVEL_PATTERN:-%5p} %clr([%8X{transactionId} %X{MethodName}]) --- [%t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

spring:
  profile: dvlocal

management:
  endpoint:
    web:
      exposure:
        include: "*"
  info:
    git:
      mode: "full"